FROM debian:latest

RUN apt-get update
RUN apt-get dist-upgrade

###
# Don't touch anything above this.
###

MAINTAINER youremail@domain.ext

#RUN apt-get install ...

#RUN ...

#...

#EXPOSE ...

#CMD ["..."]
